name = "process_waiter"
version = "1.0.0"
description = "Wait for Erlang processes to exit"

licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "process-waiter" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = "~> 0.32"
gleam_erlang = "~> 0.23"

[dev-dependencies]
gleeunit = "~> 1.0"
